modLoader="javafml" 
loaderVersion="[43,)" 
license="All rights reserved"
issueTrackerURL="https://github.com/Caltinor/Project-MMO-2.0/issues/"

[[mods]]
modId="pmmo"
version="${file.jarVersion}"
displayName="Project MMO"
logoFile="star.png"
credits="MMD were there when this mod needed them, including the start"
authors="Harmonised"
description='''
Adds many different skills and benefits thanks to the skills to the game!
'''

[[dependencies.pmmo]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43.1.20,)"
    ordering="NONE"
    side="BOTH"  

[[dependencies.pmmo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
